disabled_rules:
  - superfluous_disable_command

excluded: # paths to ignore during linting. Takes precedence over `included`.    
  - Pods 
  - Carthage   
  - TeamWork/Resources/Generated/R/R.generated.swift
  - TeamWork/Resources/Generated/Sourcery/AutoEquatable.generated.swift
  - TeamWork/Resources/Generated/Sourcery/AutoMockable.generated.swift
  - TeamWork/Resources/Generated/Sourcery/AutoCodable.generated.swift
  - Domain/Resources/Generated/Sourcery/AutoEquatable.generated.swift

identifier_name:
  excluded:
    - id
    - rx

line_length:
  warning: 120