disabled_rules:
  - superfluous_disable_command

excluded: # paths to ignore during linting. Takes precedence over `included`.    
  - Pods 
  - Carthage   
  - TeamWork/Common/Extensions/UIImage+DominantColors.swift
  - TeamWork/Resources/Generated/R/R.generated.swift  
  - TeamWork/Resources/Generated/Sourcery/*.generated.swift
  - Domain/Resources/Generated/Sourcery/*.generated.swift
  - TeamworkAPI/Resources/Sourcery/Generated/*.generated.swift  

identifier_name:
  excluded:
    - id
    - rx
    - to

line_length:
  warning: 120